//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Address: Codable {

    public var type: String?
    public var name: String?
    public var address: String?
    public var currencyCode: String?

    public init(type: String? = nil, name: String? = nil, address: String? = nil, currencyCode: String? = nil) {
        self.type = type
        self.name = name
        self.address = address
        self.currencyCode = currencyCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
        case address
        case currencyCode = "currency_code"
    }

}
