//
// Order.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Order: Codable {

    public var pairName: String?
    public var amountBase: String?
    public var isDefaultRule: Bool?
    public var withdrawAddress: Address?
    public var depositAddress: Address?
    public var amountQuote: String?
    public var createdOn: Date?

    public init(pairName: String? = nil, amountBase: String? = nil, isDefaultRule: Bool? = nil, withdrawAddress: Address? = nil, depositAddress: Address? = nil, amountQuote: String? = nil, createdOn: Date? = nil) {
        self.pairName = pairName
        self.amountBase = amountBase
        self.isDefaultRule = isDefaultRule
        self.withdrawAddress = withdrawAddress
        self.depositAddress = depositAddress
        self.amountQuote = amountQuote
        self.createdOn = createdOn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pairName = "pair_name"
        case amountBase = "amount_base"
        case isDefaultRule = "is_default_rule"
        case withdrawAddress = "withdraw_address"
        case depositAddress = "deposit_address"
        case amountQuote = "amount_quote"
        case createdOn = "created_on"
    }

}
